name: tile
title: Place tiles on the floor

time_limit: 1
memory_limit: 64

subtask:
  - score: 5
    testdata: 
      - sample1
      - sample2
      - test-1-1
      - test-1-2

  - score: 15
    testdata: 
      - sample1
      - sample2
      - test-1-1
      - test-1-2
      - test-2-1
      - test-2-2
      - test-2-3
      - test-2-4
      - test-2-5
      - test-2-6
      - test-2-7
      - test-2-8
      - test-2-9
      - test-2-10
      - test-2-11

  - score: 20
    testdata: 
      - sample1
      - sample2
      - test-1-1
      - test-1-2
      - test-2-1
      - test-2-2
      - test-2-3
      - test-2-4
      - test-2-5
      - test-2-6
      - test-2-7
      - test-2-8
      - test-2-9
      - test-2-10
      - test-2-11
      - test-3-1
      - test-3-2
      - test-3-3
      - test-3-4
      - test-3-5
      - test-3-6

  - score: 60
    testdata: 
      - sample1
      - sample2
      - test-1-1
      - test-1-2
      - test-2-1
      - test-2-2
      - test-2-3
      - test-2-4
      - test-2-5
      - test-2-6
      - test-2-7
      - test-2-8
      - test-2-9
      - test-2-10
      - test-2-11
      - test-3-1
      - test-3-2
      - test-3-3
      - test-3-4
      - test-3-5
      - test-3-6
      - test-4-1
      - test-4-2
      - test-4-3
      - test-4-4
      - test-4-5
      - test-4-6
      - test-4-7
      - test-4-8
      - test-4-9
      - test-4-10
